# Generated by Django 4.1.2 on 2022-10-31 16:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingJobsPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='tittle',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
