# Generated by Django 4.1.2 on 2022-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingJobsPage', '0002_jobposting_tittle_alter_jobposting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
