# Generated by Django 4.1.2 on 2022-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingJobsPage', '0003_jobposting_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['skill'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills',
            field=models.ManyToManyField(to='landingJobsPage.skill'),
        ),
    ]
